# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function counts the number of neighboring/touching pixels in a 2D binary image
#'
#' @name count_neighbors
#' @param im A boolean matrix representing a binary image
#' @param diagonal Whether to count diagonal elements as valid neighbors
#' @return A matrix of the same size as \code{im} containing the number of neighboring pixels
#'
#' @details This is an internal function used by geom_outline to clean up outlines
#' @author Michael Hallquist
NULL

count_neighbors <- function(im, diagonal = TRUE) {
    .Call(`_ggbrain_count_neighbors`, im, diagonal)
}

#' This function finds holes by flood filling TRUE into a 2D binary image, starting from the edge
#'
#' @name fill_from_edge
#' @param im A boolean matrix representing a binary image
#' @param nedges An integer specifying how many starting points along the edge to use for
#'   filling TRUE. The starts are northwest (1), southwest (2), southeast (3), and northeast (4).
#'   The compute time increases with the number of starts.
#' @return A matrix of the same size as \code{im} containing the number of neighboring pixels
#'
#' @details This is an internal function used by geom_outline to clean up outlines
#' @author Michael Hallquist
NULL

fill_from_edge <- function(im, nedges = 2L) {
    .Call(`_ggbrain_fill_from_edge`, im, nedges)
}

#' This function flood fills a binary image with TRUE for any value of FALSE
#'
#' @name flood_fill
#' @param im A boolean matrix reference representing a binary image
#' @param x the starting x position for fill
#' @param y the starting y position for fill
#' @param r the number of rows in im
#' @param c the number of columns in im
#' @return Nothing. The matrix \code{im} is modified in place (by reference)
#'
#' @details This is an internal function used by geom_outline to clean up outlines
#' @author Michael Hallquist
NULL

flood_fill <- function(im, x, y, r, c) {
    invisible(.Call(`_ggbrain_flood_fill`, im, x, y, r, c))
}

